name: Core Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  test-core:
    name: Test Core Logic
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore src/Darklands.Core.csproj
      
    - name: Build Core
      run: dotnet build src/Darklands.Core.csproj --configuration Release --no-restore
      
    - name: Test Core
      run: dotnet test tests/Darklands.Core.Tests.csproj --configuration Release --no-build --verbosity normal --logger:"console;verbosity=detailed"
      
    # Optional: Add code coverage
    - name: Test with coverage
      run: |
        dotnet test tests/Darklands.Core.Tests.csproj \
          --configuration Release \
          --collect:"XPlat Code Coverage" \
          --results-directory ./coverage
      
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        directory: ./coverage
        flags: unittests
        name: core-coverage
        fail_ci_if_error: false

  # Architecture tests run separately for fast feedback
  architecture-tests:
    name: Architecture Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Run architecture tests
      run: |
        dotnet test tests/Darklands.Core.Tests.csproj \
          --configuration Release \
          --filter "Category=Architecture" \
          --verbosity normal